# Generated by Django 4.2.7 on 2025-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="oauth2_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_auth_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_client_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_scope",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_token_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("none", "No Authentication"),
                    ("basic", "Basic Authentication"),
                    ("api_key", "API Key"),
                    ("bearer", "Bearer Token"),
                    ("oauth2", "OAuth 2.0"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
