# Generated by Django 4.2.7 on 2025-08-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0002_credential_oauth2_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="custom_auth_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom authentication configuration",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("none", "No Authentication"),
                    ("basic", "Basic Authentication"),
                    ("api_key", "API Key"),
                    ("bearer", "Bearer Token"),
                    ("oauth2", "OAuth 2.0"),
                    ("custom", "Custom Authentication"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CustomAuthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(
                        help_text="Name of the authentication parameter (e.g., 'Authorization', 'X-Auth-Token')",
                        max_length=100,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("static", "Static Value"),
                            ("dynamic", "Dynamic from API"),
                        ],
                        default="static",
                        max_length=10,
                    ),
                ),
                (
                    "static_value",
                    models.TextField(
                        blank=True, help_text="Static authentication value"
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True, help_text="API endpoint to fetch token from"
                    ),
                ),
                (
                    "api_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "api_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Headers for token API request",
                    ),
                ),
                (
                    "api_query_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Query parameters for token API request",
                    ),
                ),
                (
                    "api_body",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request body for token API request",
                    ),
                ),
                (
                    "response_path",
                    models.CharField(
                        blank=True,
                        help_text="JSON path to extract token from response (e.g., 'access_token', 'data.token', 'result.auth_key')",
                        max_length=200,
                    ),
                ),
                (
                    "cache_duration_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="How long to cache the fetched token (in minutes)",
                    ),
                ),
                (
                    "cached_token",
                    models.TextField(blank=True, help_text="Cached token value"),
                ),
                (
                    "cached_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was cached", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_auth_configs",
                        to="connectors.credential",
                    ),
                ),
            ],
            options={
                "ordering": ["credential__name", "key_name"],
                "unique_together": {("credential", "key_name")},
            },
        ),
    ]
