# Generated by Django 4.2.7 on 2025-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0003_credential_custom_auth_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoraction",
            name="headers_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Header metadata: {header_name: {mandatory: bool, description: str}}",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="query_params_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Query parameter metadata: {param_name: {mandatory: bool, description: str}}",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="request_body_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Request body parameter definitions: {param_name: {mandatory: bool, type: str, default: any, description: str}}",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="request_body_template",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Request body template with parameter placeholders",
            ),
        ),
        migrations.AlterField(
            model_name="connectoraction",
            name="headers",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom headers with values"
            ),
        ),
        migrations.AlterField(
            model_name="connectoraction",
            name="query_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default query parameters with values",
            ),
        ),
    ]
