# Generated by Django 4.2.7 on 2025-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0004_connectoraction_headers_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoraction",
            name="path_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default path parameters with values",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="path_params_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Path parameter metadata: {param_name: {mandatory: bool, description: str}}",
            ),
        ),
        migrations.AlterField(
            model_name="connectoraction",
            name="endpoint_path",
            field=models.CharField(
                help_text="Path to append to base URL with optional templates (e.g., /api/users/{userId})",
                max_length=500,
            ),
        ),
    ]
