# Generated by Django 4.2.7 on 2025-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0005_add_path_params_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoraction",
            name="enable_custom_success_logic",
            field=models.BooleanField(
                default=False, help_text="Enable custom success criteria evaluation"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="success_criteria",
            field=models.TextField(
                blank=True,
                help_text="Custom success criteria expression (e.g., 'status == 1 && data.documentId != null')",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="success_criteria_description",
            field=models.TextField(
                blank=True,
                help_text="Description of what constitutes a successful response",
            ),
        ),
    ]
