# Generated by Django 4.2.7 on 2025-08-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0006_add_custom_success_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectoraction",
            name="action_type",
            field=models.CharField(
                choices=[("sync", "Synchronous"), ("async", "Asynchronous")],
                default="sync",
                help_text="Whether this action executes synchronously or asynchronously",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="async_failure_criteria",
            field=models.TextField(
                blank=True,
                help_text="Failure criteria for async polling (e.g., 'data.status == \"failed\" || data.error != null')",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="async_failure_description",
            field=models.TextField(
                blank=True, help_text="Description of async failure conditions"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="async_success_criteria",
            field=models.TextField(
                blank=True,
                help_text="Success criteria for async polling (e.g., 'data.status == \"completed\" && data.result != null')",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="async_success_description",
            field=models.TextField(
                blank=True, help_text="Description of async success conditions"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="async_type",
            field=models.CharField(
                blank=True,
                choices=[("polling", "Polling-based"), ("webhook", "Webhook-based")],
                help_text="Type of async execution (only for async actions)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="max_polling_attempts",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of polling attempts before giving up",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_endpoint_path",
            field=models.CharField(
                blank=True,
                help_text="Polling endpoint path (e.g., /api/jobs/{jobId}/status)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_frequency_seconds",
            field=models.IntegerField(
                default=30, help_text="Polling frequency in seconds"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom headers for polling endpoint",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_headers_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Polling header metadata"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_http_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                    ("DELETE", "DELETE"),
                ],
                default="GET",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_path_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default path parameters for polling endpoint",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_path_params_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Polling path parameter metadata"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_query_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default query parameters for polling endpoint",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_query_params_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Polling query parameter metadata"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_request_body",
            field=models.JSONField(
                blank=True, default=dict, help_text="Request body for polling endpoint"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="polling_request_body_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Polling request body parameter definitions",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="response_to_polling_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping of response fields to polling parameters: {response_path: {target_type: 'path'|'query'|'header'|'body', target_param: 'param_name', json_path: 'nested.path'}}",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_body_template",
            field=models.JSONField(
                blank=True, default=dict, help_text="Expected webhook payload structure"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_endpoint",
            field=models.URLField(
                blank=True, help_text="Webhook callback endpoint URL"
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Headers to expect in webhook callback",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                    ("DELETE", "DELETE"),
                ],
                default="POST",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_verification_token",
            field=models.CharField(
                blank=True, help_text="Token for webhook verification", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="AsyncActionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        help_text="Unique identifier for this async execution",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "initial_request_params",
                    models.JSONField(
                        default=dict, help_text="Parameters used for initial API call"
                    ),
                ),
                (
                    "initial_response",
                    models.JSONField(
                        default=dict, help_text="Response from initial API call"
                    ),
                ),
                ("initial_response_status", models.IntegerField(blank=True, null=True)),
                ("initial_called_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("polling", "Polling in Progress"),
                            ("completed", "Completed Successfully"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=15,
                    ),
                ),
                (
                    "polling_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of polling attempts made"
                    ),
                ),
                (
                    "last_polling_response",
                    models.JSONField(
                        default=dict, help_text="Most recent polling response"
                    ),
                ),
                ("last_polling_status", models.IntegerField(blank=True, null=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "final_response",
                    models.JSONField(
                        default=dict,
                        help_text="Final response when async operation completes",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if execution failed"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workflow_execution_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Associated workflow execution ID",
                        null=True,
                    ),
                ),
                (
                    "workflow_rule_id",
                    models.IntegerField(
                        blank=True, help_text="Associated workflow rule ID", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="async_executions",
                        to="connectors.connectoraction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["execution_id"], name="connectors__executi_4bcb9d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="connectors__status_e01b90_idx"
                    ),
                    models.Index(
                        fields=["workflow_execution_id"],
                        name="connectors__workflo_360190_idx",
                    ),
                ],
            },
        ),
    ]
