# Generated by Django 4.2.7 on 2025-08-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0007_connectoraction_action_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncActionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial API Call"),
                            ("polling", "Polling Attempt"),
                            ("completion", "Async Completion"),
                            ("failure", "Async Failure"),
                            ("timeout", "Max Attempts Reached"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                ("endpoint_url", models.URLField()),
                ("http_method", models.CharField(max_length=10)),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1, help_text="Which attempt this is (for polling)"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional progress notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "async_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_steps",
                        to="connectors.asyncactionexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["async_execution", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["async_execution", "step_type"],
                        name="connectors__async_e_eccc30_idx",
                    ),
                    models.Index(
                        fields=["async_execution", "created_at"],
                        name="connectors__async_e_ef1761_idx",
                    ),
                ],
            },
        ),
    ]
