# Generated by Django 4.2.7 on 2025-08-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0008_asyncactionprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asyncactionprogress",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asyncactionprogress",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional progress notes", null=True
            ),
        ),
    ]
