# Generated by Django 4.2.7 on 2025-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0009_alter_asyncactionprogress_error_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectoraction",
            name="webhook_body_template",
        ),
        migrations.RemoveField(
            model_name="connectoraction",
            name="webhook_endpoint",
        ),
        migrations.RemoveField(
            model_name="connectoraction",
            name="webhook_headers",
        ),
        migrations.RemoveField(
            model_name="connectoraction",
            name="webhook_method",
        ),
        migrations.RemoveField(
            model_name="connectoraction",
            name="webhook_verification_token",
        ),
        migrations.AddField(
            model_name="asyncactionexecution",
            name="webhook_identifier",
            field=models.CharField(
                blank=True,
                help_text="Identifier for static webhook matching",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="asyncactionexecution",
            name="webhook_received",
            field=models.BooleanField(
                default=False, help_text="Whether webhook callback was received"
            ),
        ),
        migrations.AddField(
            model_name="asyncactionexecution",
            name="webhook_received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When webhook callback was first received",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asyncactionexecution",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Generated or static webhook URL for this execution",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_failure_criteria",
            field=models.TextField(
                blank=True,
                help_text="Failure criteria for webhook responses (e.g., 'data.status == \"failed\"')",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_identifier_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping for static webhooks: {'initial_response_field': 'webhook_payload_field'}",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_success_criteria",
            field=models.TextField(
                blank=True,
                help_text="Success criteria for webhook responses (e.g., 'data.status == \"completed\"')",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_timeout_seconds",
            field=models.IntegerField(
                default=3600,
                help_text="Timeout for webhook completion (default: 1 hour)",
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_type",
            field=models.CharField(
                blank=True,
                choices=[("dynamic", "Dynamic URL"), ("static", "Static URL")],
                help_text="Type of webhook URL generation",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_url_injection_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("path", "Path Parameter"),
                    ("query", "Query Parameter"),
                    ("body", "Body Parameter"),
                ],
                help_text="How to inject webhook URL into initial API call",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="webhook_url_injection_param",
            field=models.CharField(
                blank=True,
                help_text="Parameter name/path for URL injection (e.g., 'webhook_url' or 'callback.url')",
                max_length=100,
            ),
        ),
    ]
