# Generated by Django 4.2.7 on 2025-12-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0011_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_format",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON format specification for the event payload",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of parameter names in scope for this event",
            ),
        ),
    ]
