# Generated by Django 4.2.7 on 2025-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0012_event_event_format_event_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="acknowledgement_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether to send acknowledgement when webhook is received",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="acknowledgement_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Payload to send in acknowledgement response",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="acknowledgement_status_code",
            field=models.IntegerField(
                default=200, help_text="HTTP status code to return in acknowledgement"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.IntegerField(
                help_text="System-generated 7-digit unique identifier", unique=True
            ),
        ),
    ]
