# Generated by Django 4.2.7 on 2025-12-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0013_event_acknowledgement_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="acknowledgement_type",
            field=models.CharField(
                choices=[("basic", "Basic Response"), ("custom", "Custom Response")],
                default="basic",
                help_text="Type of acknowledgement response",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="acknowledgement_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Payload to send in acknowledgement response (for custom type only)",
            ),
        ),
    ]
