# Generated by Django 4.2.7 on 2025-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0015_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Event status",
                max_length=10,
            ),
        ),
    ]
