# Generated by Django 4.2.7 on 2025-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0016_event_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["name", "-version"]},
        ),
        migrations.AddField(
            model_name="event",
            name="base_event_id",
            field=models.IntegerField(
                blank=True,
                help_text="Base event ID for grouping versions together",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="version",
            field=models.IntegerField(
                default=1, help_text="Version number of this event"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["base_event_id", "-version"],
                name="connectors__base_ev_11f5b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "status"], name="connectors__event_t_256033_idx"
            ),
        ),
    ]
