# Generated by Django 4.2.7 on 2025-12-09 07:00

from django.db import migrations


def populate_base_event_id(apps, schema_editor):
    Event = apps.get_model('connectors', 'Event')
    for event in Event.objects.all():
        if not event.base_event_id:
            event.base_event_id = event.event_id
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0017_alter_event_options_event_base_event_id_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_base_event_id, reverse_code=migrations.RunPython.noop),
    ]
