# Generated by Django 4.2.7 on 2025-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0018_populate_base_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequence",
            name="flow_edges",
            field=models.JSONField(
                blank=True, default=list, help_text="ReactFlow edges configuration"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="flow_nodes",
            field=models.JSONField(
                blank=True, default=list, help_text="ReactFlow nodes configuration"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="trigger_events",
            field=models.JSONField(
                blank=True, default=list, help_text="Events that trigger this sequence"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="version",
            field=models.CharField(
                default="1.0", help_text="Sequence version", max_length=20
            ),
        ),
    ]
