# Generated by Django 4.2.7 on 2025-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0019_sequence_flow_edges_sequence_flow_nodes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequence",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sequence variables for storing workflow data",
            ),
        ),
    ]
