# Generated by Django 4.2.7 on 2025-12-19 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connectors", "0020_add_sequence_variables"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "trigger_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Event payload that triggered this execution",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "final_output",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Final output/results of the sequence",
                    ),
                ),
                (
                    "variables_state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Final state of sequence variables",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="connectors.sequence",
                    ),
                ),
                (
                    "triggered_by_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="connectors.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.CharField(
                        help_text="ID of the node in the flow", max_length=100
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("trigger", "Trigger"),
                            ("action", "Action"),
                            ("condition", "Condition"),
                            ("event", "Event"),
                            ("custom_rule", "Custom Rule"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        blank=True, help_text="Display name of the node", max_length=200
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Log message describing what happened"),
                ),
                ("status", models.CharField(default="started", max_length=20)),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Input data for this node"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Output data from this node"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Error details if node failed",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata like retry count, API response, etc.",
                    ),
                ),
                (
                    "sequence_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="connectors.sequenceexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_execution", "started_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="Cached email in case user is deleted",
                        max_length=254,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("connector", "Connector"),
                            ("credential", "Credential"),
                            ("action", "Connector Action"),
                            ("event", "Event"),
                            ("sequence", "Sequence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("activated", "Activated"),
                            ("deactivated", "Deactivated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(help_text="ID of the entity that was modified"),
                ),
                (
                    "entity_name",
                    models.CharField(
                        help_text="Name of the entity for quick reference",
                        max_length=200,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Human-readable description of the action"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Summary of what changed (before/after values)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sequenceexecution",
            index=models.Index(
                fields=["sequence", "-started_at"],
                name="connectors__sequenc_c78bdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sequenceexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="connectors__status_f6d76c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["sequence_execution", "started_at"],
                name="connectors__sequenc_3bf1f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="executionlog",
            index=models.Index(
                fields=["log_level", "started_at"],
                name="connectors__log_lev_7a9572_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["entity_type", "-created_at"],
                name="connectors__entity__c5ebc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="connectors__action__8000ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "-created_at"], name="connectors__user_id_737a51_idx"
            ),
        ),
    ]
