# Generated by Django 4.2.7 on 2025-12-19 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("connectors", "0021_sequenceexecution_executionlog_activitylog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("system", "System Connector"),
                    ("custom", "Custom Connector"),
                ],
                default="custom",
                help_text="System or custom connector",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Active or inactive status",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="origin_type",
            field=models.CharField(
                choices=[("system", "System Action"), ("custom", "Custom Action")],
                default="custom",
                help_text="System or custom action",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="connectoraction",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="Active or inactive status",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="credential_type",
            field=models.CharField(
                choices=[
                    ("system", "System Credential Profile"),
                    ("custom", "Custom Credential Profile"),
                ],
                default="custom",
                help_text="System or custom credential profile",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CredentialSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this credential set (e.g., 'Production API Key', 'Staging OAuth')",
                        max_length=100,
                    ),
                ),
                (
                    "credential_values",
                    models.JSONField(
                        default=dict, help_text="Actual credential values"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the default credential set for this profile?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credential_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_sets",
                        to="connectors.credential",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("credential", "name")},
            },
        ),
    ]
