# Generated by Django 4.2.7 on 2025-12-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0022_connector_connector_type_connector_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="api_key_header",
            field=models.CharField(
                blank=True,
                default="X-API-Key",
                help_text="Header name for API key (e.g., 'X-API-Key', 'Authorization')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="custom_auth_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom authentication structure configuration (field names, types, descriptions)",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="oauth2_auth_url",
            field=models.URLField(blank=True, help_text="OAuth2 authorization URL"),
        ),
        migrations.AlterField(
            model_name="credential",
            name="oauth2_scope",
            field=models.CharField(
                blank=True, help_text="OAuth2 scope", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="oauth2_token_url",
            field=models.URLField(blank=True, help_text="OAuth2 token URL"),
        ),
        migrations.AlterField(
            model_name="credentialset",
            name="credential_values",
            field=models.JSONField(
                default=dict, help_text="Actual secret credential values"
            ),
        ),
    ]
