# Generated by Django 4.2.7 on 2025-12-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0023_alter_credential_api_key_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequenceexecution",
            name="browser",
            field=models.CharField(
                blank=True, help_text="Browser information", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the request that triggered this execution",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="os",
            field=models.CharField(
                blank=True,
                help_text="Operating system information",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="User agent string from the triggering request",
                max_length=500,
                null=True,
            ),
        ),
    ]
