# Generated by Django 4.2.7 on 2025-12-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0024_sequenceexecution_browser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sequenceexecution",
            name="browser",
        ),
        migrations.RemoveField(
            model_name="sequenceexecution",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="sequenceexecution",
            name="os",
        ),
        migrations.RemoveField(
            model_name="sequenceexecution",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="trigger_browser",
            field=models.CharField(
                blank=True,
                help_text="Browser used to trigger the event",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="trigger_device",
            field=models.CharField(
                blank=True,
                help_text="Device type (desktop, mobile, tablet, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="trigger_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address that triggered the event", null=True
            ),
        ),
        migrations.AddField(
            model_name="sequenceexecution",
            name="trigger_os",
            field=models.CharField(
                blank=True,
                help_text="Operating system of the triggering device",
                max_length=100,
            ),
        ),
    ]
