# Generated by Django 4.2.7 on 2025-12-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0025_add_trigger_source_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="user_browser",
            field=models.CharField(
                blank=True, help_text="Browser used by the user", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_device",
            field=models.CharField(
                blank=True,
                help_text="Device type (desktop, mobile, tablet, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_os",
            field=models.CharField(
                blank=True, help_text="Operating system of the user", max_length=100
            ),
        ),
    ]
