# Generated by Django 4.2.7 on 2025-12-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0026_add_user_device_info_to_activity_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuth2State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        db_index=True,
                        help_text="Random unique state string for OAuth2 flow",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "set_name",
                    models.CharField(
                        help_text="Name for the credential set to be created",
                        max_length=100,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to set this as default credential set",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect user after successful authorization",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="State expires after this time (typically 10 minutes)"
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        help_text="Credential profile this authorization is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth2_states",
                        to="connectors.credential",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["state"], name="connectors__state_c884d8_idx"),
                    models.Index(
                        fields=["expires_at"], name="connectors__expires_d8f036_idx"
                    ),
                ],
            },
        ),
    ]
