# Generated by Django 4.2.7 on 2025-12-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0027_add_oauth2_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="oauth2_token_header",
            field=models.CharField(
                blank=True,
                default="Authorization",
                help_text="Header name for passing OAuth2 token (e.g., 'Authorization')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="oauth2_token_prefix",
            field=models.CharField(
                blank=True,
                default="Bearer",
                help_text="Prefix before token value (e.g., 'Bearer', 'Zoho-oauthtoken')",
                max_length=50,
            ),
        ),
    ]
