# Generated by Django 4.2.7 on 2025-08-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_name", models.CharField(max_length=255)),
                ("connector_name", models.CharField(max_length=255)),
                ("http_method", models.CharField(max_length=10)),
                ("endpoint_url", models.URLField()),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_params", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("not_found", "Action Not Found"),
                            ("validation_error", "Validation Error"),
                            ("auth_error", "Authentication Error"),
                            ("network_error", "Network Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("http_status_code", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("request_timestamp", models.DateTimeField()),
                ("response_timestamp", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "api_called",
                    models.BooleanField(
                        default=True, help_text="Whether actual HTTP call was made"
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_call_logs",
                        to="workflows.ruleexecution",
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_call_logs",
                        to="workflows.workflowexecution",
                    ),
                ),
                (
                    "workflow_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_call_logs",
                        to="workflows.workflowrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_execution", "-created_at"],
                        name="workflows_a_workflo_2547d0_idx",
                    ),
                    models.Index(
                        fields=["workflow_rule", "-created_at"],
                        name="workflows_a_workflo_8aa404_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="workflows_a_status_f7da8d_idx",
                    ),
                    models.Index(
                        fields=["action_name", "connector_name"],
                        name="workflows_a_action__4a8627_idx",
                    ),
                ],
            },
        ),
    ]
